package mocks

import (
	cf "github.com/cloudfoundry/go-cfclient/v3/resource"
	mock "github.com/stretchr/testify/mock"
)

// PAASClient is an autogenerated mock type for the PAASClient type
type PAASClient struct {
	mock.Mock
}

// AssociateOrgAuditorByUsername provides a mock function with given fields: orgID, userName
func (_m *PAASClient) AssociateOrgAuditorByUsername(orgID string, userName string) (*cf.Role, error) {
	ret := _m.Called(orgID, userName)

	var r0 *cf.Role
	if rf, ok := ret.Get(0).(func(string, string) *cf.Role); ok {
		r0 = rf(orgID, userName)
	} else {
		r0 = ret.Get(0).(*cf.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(orgID, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AssociateOrgUserByUsername provides a mock function with given fields: orgID, userName
func (_m *PAASClient) AssociateOrgUserByUsername(orgID string, userName string) (*cf.Role, error) {
	ret := _m.Called(orgID, userName)

	var r0 *cf.Role
	if rf, ok := ret.Get(0).(func(string, string) *cf.Role); ok {
		r0 = rf(orgID, userName)
	} else {
		r0 = ret.Get(0).(*cf.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(orgID, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AssociateSpaceAuditorByUsername provides a mock function with given fields: spaceID, userName
func (_m *PAASClient) AssociateSpaceAuditorByUsername(spaceID string, userName string) (*cf.Role, error) {
	ret := _m.Called(spaceID, userName)

	var r0 *cf.Role
	if rf, ok := ret.Get(0).(func(string, string) *cf.Role); ok {
		r0 = rf(spaceID, userName)
	} else {
		r0 = ret.Get(0).(*cf.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(spaceID, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AssociateSpaceDeveloperByUsername provides a mock function with given fields: spaceID, userName
func (_m *PAASClient) AssociateSpaceDeveloperByUsername(spaceID string, userName string) (*cf.Role, error) {
	ret := _m.Called(spaceID, userName)

	var r0 *cf.Role
	if rf, ok := ret.Get(0).(func(string, string) *cf.Role); ok {
		r0 = rf(spaceID, userName)
	} else {
		r0 = ret.Get(0).(*cf.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(spaceID, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: req
func (_m *PAASClient) CreateUser(guid string) (*cf.User, error) {
	ret := _m.Called(guid)

	var r0 *cf.User
	if rf, ok := ret.Get(0).(func(string) *cf.User); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(*cf.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: userID
func (_m *PAASClient) DeleteUser(userID string) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSpaceByGuid provides a mock function with given fields: guid
func (_m *PAASClient) GetSpaceByGuid(guid string) (*cf.Space, error) {
	ret := _m.Called(guid)

	var r0 *cf.Space
	if rf, ok := ret.Get(0).(func(string) *cf.Space); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(*cf.Space)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInstanceByGuid provides a mock function with given fields: guid
func (_m *PAASClient) ServiceInstanceByGuid(guid string) (*cf.ServiceInstance, error) {
	ret := _m.Called(guid)

	var r0 *cf.ServiceInstance
	if rf, ok := ret.Get(0).(func(string) *cf.ServiceInstance); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(*cf.ServiceInstance)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
